### ISSUE TITLE
Unable to run application tests when HONEYBADGER_API_KEY is not set

### ISSUE THREAD

**Issue by sparta-developers** [honeybadger-io/honeybadger-elixir#116]
We just updated from 0.6.3 to 0.7.0, and discovered that we are no longer able to run our test suite without setting `HONEYBADGER_API_KEY` in the environment. This doesn't really make sense, because the test environment is listed in `:excluded_envs` in the honeybadger config.

Our quick workaround is to add an empty `HONEYBADGER_API_KEY` to our env, but it would be better if we only had to export the variable for environments where honeybadger was actually enabled.

```
** (Mix) Could not start application honeybadger: exited in: Honeybadger.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (ArgumentError) system variable "HONEYBADGER_API_KEY" is not set
            (honeybadger) lib/honeybadger.ex:233: Honeybadger.get_env/1
            (honeybadger) lib/honeybadger.ex:255: anonymous fn/2 in Honeybadger.get_all_env/0
            (elixir) lib/enum.ex:1811: Enum."-reduce/3-lists^foldl/2-0-"/3
            (honeybadger) lib/honeybadger.ex:254: Honeybadger.get_all_env/0
            (honeybadger) lib/honeybadger.ex:146: Honeybadger.start/2
            (kernel) application_master.erl:273: :application_master.start_it_old/4
```

**Comment by sparta-developers** [comment]
Thank you!
