### ISSUE TITLE
Argument error in Honeybadger.Metrics.Server

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-elixir#41]
```sh
May 19 11:38:46 app.production app/web.1:  10:38:46.185 [error] #PID<0.814.0> running Status.Endpoint terminated 
May 19 11:38:46 app.production app/web.1:  Request: POST /graphql 
May 19 11:38:46 app.production app/web.1:  ** (exit) an exception was raised: 
May 19 11:38:46 app.production app/web.1:      ** (ArgumentError) argument error 
May 19 11:38:46 app.production app/web.1:          :erlang.send(Honeybadger.Metrics.Server, {:"$gen_cast", {:add_timing, 3}}) 
May 19 11:38:46 app.production app/web.1:          (elixir) lib/gen_server.ex:639: GenServer.do_send/2 
May 19 11:38:46 app.production app/web.1:          (status) web/router.ex:3: Status.Router."call (overridable 2)"/2 
May 19 11:38:46 app.production app/web.1:          (status) lib/plug/error_handler.ex:63: Status.Router.call/2 
May 19 11:38:46 app.production app/web.1:          (status) lib/status/endpoint.ex:1: Status.Endpoint.phoenix_pipeline/1 
May 19 11:38:46 app.production app/web.1:          (status) lib/phoenix/endpoint/render_errors.ex:34: Status.Endpoint.call/2
```

@rbishop any ideas?

**Comment by willrax** [comment]
If there are any other details I can provide, let me know.

**Comment by rbishop** [comment]
This is an interesting one. Metrics.Server definitely handles that kind of message. Any other info would really help @willrax

**Comment by willrax** [comment]
the weird thing was that the request seemed to be going through ok. I'll add the line back in and see what other details I can collect locally.

**Comment by saaji** [comment]
Not sure if it is completely related, but on my phoenix app, after live release upgrade through OTP releases `Honeybadger.Metrics.Server` often starts to fail with 

```
** (ArgumentError) argument error
    (honeybadger) lib/honeybadger/client.ex:28: Honeybadger.Client.send_metric/3 
    (honeybadger) lib/honeybadger/metrics/server.ex:49: Honeybadger.Metrics.Server.handle_info/2
    (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

=CRASH REPORT==== 27-May-2016::16:30:44 ===
  crasher:
    initial call: Elixir.Honeybadger.Metrics.Server:init/1
    pid: <0.1532.0>
    registered_name: 'Elixir.Honeybadger.Metrics.Server'
    exception exit: {badarg,
                        [{'Elixir.Honeybadger.Client',send_metric,3,
                             [{file,"lib/honeybadger/client.ex"},{line,28}]},
                         {'Elixir.Honeybadger.Metrics.Server',handle_info,2,
                             [{file,"lib/honeybadger/metrics/server.ex"},
                              {line,49}]},
                         {gen_server,try_dispatch,4,
                             [{file,"gen_server.erl"},{line,615}]},
                         {gen_server,handle_msg,5,
                             [{file,"gen_server.erl"},{line,681}]},
                         {proc_lib,init_p_do_apply,3,
                             [{file,"proc_lib.erl"},{line,240}]}]}
      in function  gen_server:terminate/7 (gen_server.erl, line 826)
    ancestors: [<0.1531.0>,<0.1530.0>]
    messages: []
    links: [<0.1531.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 78985
  neighbours:

=SUPERVISOR REPORT==== 27-May-2016::16:30:44 ===
     Supervisor: {<0.1531.0>,'Elixir.Honeybadger.Metrics.Supervisor'}
     Context:    child_terminated
     Reason:     {badarg,
                     [{'Elixir.Honeybadger.Client',send_metric,3,
                          [{file,"lib/honeybadger/client.ex"},{line,28}]},
                      {'Elixir.Honeybadger.Metrics.Server',handle_info,2,
                          [{file,"lib/honeybadger/metrics/server.ex"},
                           {line,49}]},
                      {gen_server,try_dispatch,4,
                          [{file,"gen_server.erl"},{line,615}]},
                      {gen_server,handle_msg,5,
                          [{file,"gen_server.erl"},{line,681}]},
                      {proc_lib,init_p_do_apply,3,
                          [{file,"proc_lib.erl"},{line,240}]}]}
     Offender:   [{pid,<0.1532.0>},
                  {id,'Elixir.Honeybadger.Metrics.Server'},
                  {mfargs,{'Elixir.Honeybadger.Metrics.Server',start_link,[]}},
                  {restart_type,permanent},
                  {shutdown,5000},
                  {child_type,worker}]
```

This makes the project's Metrics tab on app.honeybadger.io pretty much dead. Doing start/stop sequence on the deployed app puts things back to normal... till next upgrade.

**Comment by nurugger07** [comment]
@willrax can you provide some more detail around the issue you are having? As @rbishop the Metrics server is handling this message and shouldn't be causing an issue. I haven't been able to reproduce this locally.

**Comment by nurugger07** [comment]
@saaji I don't believe that is the same issue or related to this. If you are still having the issue, can you open a separate issue and provide as much detail as you can? 

Also, for both @saaji & @willrax can you provide version #'s?

**Comment by willrax** [comment]
Hey @nurugger07. When I add the line

```
use Honeybadger.Plug
```

To my router i get the error mentioned in the first post. I thought it might be the version number so I upgraded to 0.5.0 but the issues still persists.

**Comment by willrax** [comment]
I don't think I'm doing anything special in my setup. If it helps, it's deployed to heroku.

**Comment by nurugger07** [comment]
@willrax did you add honeybadger to your applications list in your mix file?

**Comment by willrax** [comment]
doh. It was missing from the applications list in m mix file. Such a silly error. Sorry to waste time.

**Comment by nurugger07** [comment]
@willrax no worries :) Happy to help!

@saaji can you create a new issue and provide detailed information on the steps to reproduce?

**Comment by saaji** [comment]
will double-check and get back with a new issue if problem persists

**Comment by nurugger07** [comment]
@saaji sound good. thanks!

**Comment by nurugger07** [comment]
I'm closing this issue. Thanks to everyone for your patience :)
