### ISSUE TITLE
Random test failure

### ISSUE THREAD

**Issue by mwoods79** [honeybadger-io/honeybadger-elixir#74]
```
  1) test log levels lower than :error_report are ignored (Honeybadger.LoggerTest)
     test/logger_test.exs:44
     Expected false or nil, got true
     code: :meck.called(HTTP, :post, [:_, :_, :_])
     stacktrace:
       test/logger_test.exs:51: anonymous fn/1 in Honeybadger.LoggerTest.test log levels lower than :error_report are ignored/1
       (elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2
       (elixir) lib/enum.ex:604: Enum.each/2
       test/logger_test.exs:47
```

**Comment by mwoods79** [comment]
Closing: Duplicate https://github.com/honeybadger-io/honeybadger-elixir/issues/76
